---
# task file for dgnest.authorization

- name: Update package repositories
  sudo: yes
  apt:
    update_cache: True
  when: ansible_distribution == "Ubuntu"
  tags:
    - apt
    - update_cache

- name: Install authorization package dependencies
  sudo: yes
  apt:
    name: "{{ item }}"
    state: present
  register: install_authorization_package_dependencies
  when: _authorization_package_dependencies is defined
  with_items: _authorization_package_dependencies
  tags:
    - apt
    - dependencies
- debug: var=install_authorization_package_dependencies.stdout_lines

